### ISSUE TITLE
AssertionError: must pass params to get

### ISSUE THREAD

**Issue by howdiz** [chbrown/npm-search-downloads#1]
example search 

npm-search-downloads xml --sort downloads

throws

assert.js:89
  throw new assert.AssertionError({
  ^
AssertionError: must pass params to get
    at CachingRegistryClient.get (/usr/local/lib/node_modules/npm-search-downloads/node_modules/npm/lib/cache/caching-client.js:59:3)
    at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm-search-downloads/commands/search.js:20:18)
    at doNTCallback0 (node.js:407:9)
    at process._tickCallback (node.js:336:13)

on
npm@2.14.3 /usr/local/lib/node_modules/npm

**Comment by chbrown** [comment]
I expect you're seeing that error because I didn't use a specific version for npm in my package dependencies. You might have some luck replacing `"npm": "*"` with `"npm": "2.14.10"` and rerunning `npm install`.

This package fetches download counts from the NPM downloads API as needed and stores them in a local Redis database, which means it's fragile, as you've noticed, and depends on external APIs.

I've since upgraded to a [more complicated assembly](https://github.com/search?q=user%3Achbrown+npm) of micro-services involving an npm downloads crawler, PostgreSQL database for storage with simple server, Elasticsearch backend, and a static web UI with AJAX connection to Elasticsearch and downloads database.

I have a live copy of this that works for my needs, but I'm not sure how well it'd stand up to heavy use, so it's not yet public.

**Comment by chbrown** [comment]
Yeah, that was it. Fixed as of e561b47 / [`v0.3.1`](https://www.npmjs.com/package/npm-search-downloads).
